#!/bin/bash
#
# Security Scan Script
#
# This script runs Trivy, a container vulnerability scanner, against all
# the Docker images defined in the docker-compose.yml file.
#
# Prerequisites:
#   - Docker must be installed.
#   - Trivy must be installed: https://github.com/aquasecurity/trivy
#
# Usage:
#   ./scripts/security_scan.sh

set -e

# Ensure Trivy is installed
if ! command -v trivy &> /dev/null; then
    echo "❌ ERROR: Trivy is not installed. Please install it to run this scan."
    exit 1
fi

# The docker-compose.yml is generated by deploy.sh, so we need to run that first.
# For a CI environment, you would run the deploy script to generate the file.
# For local testing, we can assume it has been generated.
COMPOSE_FILE="/opt/supabase-super-stack/docker-compose.yml"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "⚠️ WARNING: docker-compose.yml not found at $COMPOSE_FILE."
    echo "Skipping scan. Run the deploy.sh script first."
    exit 0
fi

echo "🔍 Scanning images defined in $COMPOSE_FILE..."

# Extract all unique image names from the docker-compose file
IMAGES=$(grep 'image:' "$COMPOSE_FILE" | awk '{print $2}' | sort -u)

for IMAGE in $IMAGES; do
    echo "--------------------------------------------------"
    echo "Scanning image: $IMAGE"
    echo "--------------------------------------------------"
    # Scan the image for high and critical vulnerabilities, exit if any are found
    trivy image --severity HIGH,CRITICAL --exit-code 1 "$IMAGE"
done

echo "✅ All images scanned. No high or critical vulnerabilities found."
